### PR TITLE
Smart evaluating of trigonometry

### LINKED ISSUE #187: tan(pi / 2) simplify is wrong
`"tan(pi/2)".Simplify();` returns huge integer number

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
Closes #187.
Currently, there's a table of values for sin and cos (e. g. it can find pi / 3 numerically in that table and return an analytical number), but it cannot do this for arbitrary pi * r where r is rational. That's what will be done for this issue.

### CODE REVIEW

File: Sources/AngouriMath/Functions/Simplification/Simplificator.cs [hunk 1]
```diff
@@ -237,8 +237,114 @@ internal static Entity ParaphraseInterval(Entity entity, Entity left, bool leftC
...
+                if (denominator < 0)
+                {
+                    denominator *= -1;
+                    numerator *= -1;
+                }
+                //var gcd = 
+                (Numerator, Denominator) = (numerator, denominator);
+            }
+            public static operator 
+        }*/
```
Comment (WhiteBlackGoose) [inline Sources/AngouriMath/Functions/Simplification/Simplificator.cs:348]: 🤔

File: Sources/AngouriMath/Functions/NumberTheory/Diophantine.cs [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+
+            while (true)
+            {
+                var newX = x - b;
+                var newY = y + a;
+                if (newX.Abs() + newY.Abs() >= x.Abs() + y.Abs() || x < 0)
+                    break;
+                x = newX;
+                y = newY;
+            }
```
Comment (WhiteBlackGoose) [inline Sources/AngouriMath/Functions/NumberTheory/Diophantine.cs:62]: This is absolutely awful.

File: Sources/AngouriMath/Functions/NumberTheory/Fraction.cs [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+        /// number into sum of rationals a_i / p_i^k,
+        /// where p_i is a prime number. Evaluates
+        /// lazily.
+        /// </summary>
+        internal static IEnumerable<(Integer numerator, Integer denPrime, Integer denPower)> Decompose(Integer num, Integer den)
+        {
+            var primeId = 0;
+            while (num != 0)
+            {
+                if (Expand(num, den, primeId) is var (newNum, y, denPrime, denPower, _, _))
```
Comment (WhiteBlackGoose) [inline Sources/AngouriMath/Functions/NumberTheory/Fraction.cs:22]: This is absolutely awful.

File: Sources/AngouriMath/Functions/NumberTheory/Primes.cs [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+    {
+        private static readonly List<(Integer actual, int? cache)> primes = new(capacity: 20) { (2, 2), (3, 3), (5, 5), (7, 7), (11, 11) };
+
+
+        private static void EnsurePrimesExist(int index)
+        {
+            if (index < primes.Count)
+                return;
+
+            if (index < 100)
```
Comment (WhiteBlackGoose) [inline Sources/AngouriMath/Functions/NumberTheory/Primes.cs:20]: This is absolutely awful.

**Comment by WhiteBlackGoose** [comment]
Okay... now it's time to close #187 🦆
